# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Python 🐍 distributions 📦 to PyPI

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: update version
        run: python get_latest_version.py
      - name: install deployment dependancies
        if: github.event.pull_request.merged == true
        run: |
          pip install twine
          pip install pexpect
      - name: package module
        if: github.event.pull_request.merged == true
        run: python setup.py sdist
      - name: deployment to pypi
        if: github.event.pull_request.merged == true
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: |
          twine upload dist/*
